"""empty message

Revision ID: 0fd45e49eea9
Revises: 311106c09f52
Create Date: 2021-08-30 17:58:36.183644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0fd45e49eea9"
down_revision = "311106c09f52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event_dates", "end", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "event_dates", "end_naive", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column("event_dates", "end_time")
    op.drop_column("event_dates", "start_time")
    op.drop_column("event_dates_version", "end_time")
    op.drop_column("event_dates_version", "start_time")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_dates_version",
        sa.Column("start_time", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event_dates_version",
        sa.Column("end_time", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event_dates",
        sa.Column("start_time", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event_dates",
        sa.Column("end_time", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "event_dates", "end_naive", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "event_dates", "end", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
