"""empty message

Revision ID: 311106c09f52
Revises: b36658b8005b
Create Date: 2021-08-17 13:21:45.964590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "311106c09f52"
down_revision = "b36658b8005b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event_dates", sa.Column("end_time", sa.Boolean(), nullable=True))
    op.add_column("event_dates", sa.Column("start_time", sa.Boolean(), nullable=True))
    op.add_column(
        "event_dates_version",
        sa.Column("end_time", sa.Boolean(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event_dates_version",
        sa.Column("start_time", sa.Boolean(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_dates_version", "start_time")
    op.drop_column("event_dates_version", "end_time")
    op.drop_column("event_dates", "start_time")
    op.drop_column("event_dates", "end_time")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
