"""empty message

Revision ID: 000cd5209f06
Revises: 7242ba3a5ac5
Create Date: 2021-12-02 13:14:21.861656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000cd5209f06'
down_revision = '7242ba3a5ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_date_artists', sa.Column('start', sa.DateTime(), nullable=True))
    op.add_column('event_date_artists', sa.Column('start_naive', sa.DateTime(), nullable=True))
    op.add_column('event_date_artists_version', sa.Column('start', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('event_date_artists_version', sa.Column('start_naive', sa.DateTime(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_date_artists_version', 'start_naive')
    op.drop_column('event_date_artists_version', 'start')
    op.drop_column('event_date_artists', 'start_naive')
    op.drop_column('event_date_artists', 'start')
    # ### end Alembic commands ###
