"""empty message

Revision ID: 00be8cc1fb1b
Revises: ce4e74083eab
Create Date: 2024-06-09 01:36:12.556731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00be8cc1fb1b'
down_revision = 'ce4e74083eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_date_tickets_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('event_date_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('price_min', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('price_max', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('price_currency_code', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_event_date_tickets_version_end_transaction_id'), 'event_date_tickets_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_event_date_tickets_version_operation_type'), 'event_date_tickets_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_event_date_tickets_version_transaction_id'), 'event_date_tickets_version', ['transaction_id'], unique=False)
    op.create_table('event_date_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_date_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('price_currency_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['event_dates.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('event_dates', 'ticket_url')
    op.drop_column('event_dates_version', 'ticket_url')
    op.drop_column('rrules', 'default_ticket_url')
    op.drop_column('rrules_version', 'default_ticket_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rrules_version', sa.Column('default_ticket_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rrules', sa.Column('default_ticket_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_dates_version', sa.Column('ticket_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_dates', sa.Column('ticket_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('event_date_tickets')
    op.drop_index(op.f('ix_event_date_tickets_version_transaction_id'), table_name='event_date_tickets_version')
    op.drop_index(op.f('ix_event_date_tickets_version_operation_type'), table_name='event_date_tickets_version')
    op.drop_index(op.f('ix_event_date_tickets_version_end_transaction_id'), table_name='event_date_tickets_version')
    op.drop_table('event_date_tickets_version')
    # ### end Alembic commands ###
