"""empty message

Revision ID: 15aede430eac
Revises: f6653e8a7777
Create Date: 2021-11-16 12:06:31.805724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "15aede430eac"
down_revision = "f6653e8a7777"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    edit_action = postgresql.ENUM("create", "update", "delete", name="edit_action")
    edit_action.create(op.get_bind())

    op.add_column(
        "suggested_edits",
        sa.Column(
            "action",
            sa.Enum("create", "update", "delete", name="edit_action"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suggested_edits", "action")
    edit_action = postgresql.ENUM("create", "update", "delete", name="edit_action")
    edit_action.drop(op.get_bind())

    # ### end Alembic commands ###
