"""empty message

Revision ID: 1d2dad4acddc
Revises: a75eb0506da0
Create Date: 2025-05-28 06:59:41.102707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d2dad4acddc'
down_revision = 'a75eb0506da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_usage_language_daily',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_language_hourly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_language_monthly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_remote_daily',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('remote', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_remote_hourly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('remote', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_remote_monthly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('remote', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_server_daily',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('server', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_server_hourly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('server', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_server_monthly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('server', sa.String(length=128), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_url_daily',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_url_hourly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_url_monthly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_useragent_daily',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('useragent', sa.String(length=512), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_useragent_hourly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('useragent', sa.String(length=512), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('flask_usage_useragent_monthly',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('useragent', sa.String(length=512), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_usage_useragent_monthly')
    op.drop_table('flask_usage_useragent_hourly')
    op.drop_table('flask_usage_useragent_daily')
    op.drop_table('flask_usage_url_monthly')
    op.drop_table('flask_usage_url_hourly')
    op.drop_table('flask_usage_url_daily')
    op.drop_table('flask_usage_server_monthly')
    op.drop_table('flask_usage_server_hourly')
    op.drop_table('flask_usage_server_daily')
    op.drop_table('flask_usage_remote_monthly')
    op.drop_table('flask_usage_remote_hourly')
    op.drop_table('flask_usage_remote_daily')
    op.drop_table('flask_usage_language_monthly')
    op.drop_table('flask_usage_language_hourly')
    op.drop_table('flask_usage_language_daily')
    # ### end Alembic commands ###
