"""empty message

Revision ID: 1d4cdddaee45
Revises: 97dbf5be6c96
Create Date: 2025-07-30 21:26:42.257440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4cdddaee45'
down_revision = '97dbf5be6c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('events_version', sa.Column('featured', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'featured')
    op.drop_column('events', 'featured')
    # ### end Alembic commands ###
