"""empty message

Revision ID: 27f2400c56cd
Revises: 6ee378b84f77
Create Date: 2021-12-12 21:24:39.836738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f2400c56cd'
down_revision = '6ee378b84f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'email')
    # ### end Alembic commands ###
