"""empty message

Revision ID: 2b2c563827ad
Revises: 55053bc1a28d
Create Date: 2021-12-24 12:05:23.279007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2c563827ad'
down_revision = '55053bc1a28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('image_med_filename', sa.String(), nullable=True))
    op.add_column('media_items_version', sa.Column('image_med_filename', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items_version', 'image_med_filename')
    op.drop_column('media_items', 'image_med_filename')
    # ### end Alembic commands ###
