"""empty message

Revision ID: 2b38c63195ff
Revises: 4c2d5c7f9f01
Create Date: 2026-04-22 05:32:15.952411

"""
from alembic import op
import sqlalchemy as sa
from pmapi.db_types import Vector


# revision identifiers, used by Alembic.
revision = '2b38c63195ff'
down_revision = '4c2d5c7f9f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_search_embedding', table_name='events', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('events_version', sa.Column('search_embedding', Vector(dimensions=1536), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'search_embedding')
    op.create_index('idx_events_search_embedding', 'events', ['search_embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
