"""empty message

Revision ID: 2d09fb096713
Revises: 15aede430eac
Create Date: 2021-11-18 17:36:52.404957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d09fb096713'
down_revision = '15aede430eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_edits', sa.Column('object_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_edits', 'object_type')
    # ### end Alembic commands ###
