"""empty message

Revision ID: 2f7da62f5bc8
Revises: 82c2ac06ce09
Create Date: 2023-04-26 09:08:21.096697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7da62f5bc8'
down_revision = '82c2ac06ce09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_contributions', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_contributions', 'rating')
    # ### end Alembic commands ###
