"""empty message

Revision ID: 37062e5d7acf
Revises: b0da8c191b81
Create Date: 2023-06-22 09:57:24.417472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37062e5d7acf'
down_revision = 'b0da8c191b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alias', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('description', sa.String(length=1000), nullable=True))
    op.create_foreign_key(None, 'users', 'media_items', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'description')
    op.drop_column('users', 'avatar_id')
    op.drop_column('users', 'alias')
    # ### end Alembic commands ###
