"""empty message

Revision ID: 3ac0642ae279
Revises: fab1fa8cb55f
Create Date: 2021-07-12 22:32:09.207845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3ac0642ae279"
down_revision = "fab1fa8cb55f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_contributions",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", postgresql.UUID(), nullable=False),
        sa.Column("event_id", postgresql.UUID(), nullable=False),
        sa.Column("event_date_id", postgresql.UUID(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("status", sa.SmallInteger(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("hotness", sa.Float(precision=15, asdecimal=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_date_id"],
            ["event_dates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_contribution_downvotes",
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("event_contribution_id", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_contribution_id"],
            ["event_contributions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.create_table(
        "event_contribution_upvotes",
        sa.Column("user_id", postgresql.UUID(), nullable=True),
        sa.Column("event_contribution_id", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_contribution_id"],
            ["event_contributions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.create_table(
        "media_items",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", postgresql.UUID(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("type", sa.Enum("image", "video", name="media_type"), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("thumb_filename", sa.String(), nullable=False),
        sa.Column("image_filename", sa.String(), nullable=True),
        sa.Column("video_low_filename", sa.String(), nullable=True),
        sa.Column("video_med_filename", sa.String(), nullable=True),
        sa.Column("video_high_filename", sa.String(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("contribution_id", postgresql.UUID(), nullable=True),
        sa.Column("event_id", postgresql.UUID(), nullable=False),
        sa.Column("event_date_id", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contribution_id"],
            ["event_contributions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_date_id"],
            ["event_dates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", postgresql.UUID(), nullable=True),
        sa.Column("open", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("event_contribution_id", postgresql.UUID(), nullable=True),
        sa.Column("event_id", postgresql.UUID(), nullable=True),
        sa.Column("media_item_id", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_contribution_id"],
            ["event_contributions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_item_id"],
            ["media_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("album_item_downvotes")
    op.drop_table("album_item_upvotes")
    op.drop_table("album_items")
    op.drop_constraint("events_featured_album_id_fkey", "events", type_="foreignkey")
    op.drop_column("events", "featured_album_id")
    op.drop_column("events_version", "featured_album_id")
    op.drop_table("event_albums")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events_version",
        sa.Column(
            "featured_album_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "featured_album_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "events_featured_album_id_fkey",
        "events",
        "event_albums",
        ["featured_album_id"],
        ["id"],
    )
    op.create_table(
        "event_albums",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("event_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("caption", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name="event_albums_creator_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="event_albums_event_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="event_albums_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "album_item_upvotes",
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "album_item_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["album_item_id"],
            ["album_items.id"],
            name="album_item_upvotes_album_item_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="album_item_upvotes_user_id_fkey"
        ),
    )
    op.create_table(
        "album_item_downvotes",
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "album_item_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["album_item_id"],
            ["album_items.id"],
            name="album_item_downvotes_album_item_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="album_item_downvotes_user_id_fkey"
        ),
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    op.create_table(
        "album_items",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("creator_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("thumb_filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("caption", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("album_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("event_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("status", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("hotness", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM("image", "video", name="album_item_type"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["album_id"], ["event_albums.id"], name="album_items_album_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name="album_items_creator_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="album_items_event_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="album_items_pkey"),
    )
    op.drop_table("reports")
    op.drop_table("media_items")
    op.drop_table("event_contribution_upvotes")
    op.drop_table("event_contribution_downvotes")
    op.drop_table("event_contributions")
    # ### end Alembic commands ###
