"""empty message

Revision ID: 466b435f3676
Revises: 37062e5d7acf
Create Date: 2023-08-02 10:12:07.702322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466b435f3676'
down_revision = '37062e5d7acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('full_description', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('full_description_attribute', sa.Text(), nullable=True))
    op.add_column('events_version', sa.Column('full_description', sa.Text(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('full_description_attribute', sa.Text(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'full_description_attribute')
    op.drop_column('events_version', 'full_description')
    op.drop_column('events', 'full_description_attribute')
    op.drop_column('events', 'full_description')
    # ### end Alembic commands ###
