"""empty message

Revision ID: 52aa828365a5
Revises: 8f57b9b69a09
Create Date: 2024-12-09 00:29:03.473728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52aa828365a5'
down_revision = '8f57b9b69a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Set the default value for existing rows
    op.execute('UPDATE users SET login_attempts = 0')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_attempts')
    # ### end Alembic commands ###
