"""empty message

Revision ID: 54af5853e19e
Revises: 5c230ffb3f3c
Create Date: 2021-11-09 15:13:12.528059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54af5853e19e'
down_revision = '5c230ffb3f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clusters_10_centroid', table_name='clusters_10')
    op.drop_index('idx_clusters_11_centroid', table_name='clusters_11')
    op.drop_index('idx_clusters_12_centroid', table_name='clusters_12')
    op.drop_index('idx_clusters_13_centroid', table_name='clusters_13')
    op.drop_index('idx_clusters_14_centroid', table_name='clusters_14')
    op.drop_index('idx_clusters_15_centroid', table_name='clusters_15')
    op.drop_index('idx_clusters_16_centroid', table_name='clusters_16')
    op.drop_index('idx_clusters_2_centroid', table_name='clusters_2')
    op.drop_index('idx_clusters_3_centroid', table_name='clusters_3')
    op.drop_index('idx_clusters_4_centroid', table_name='clusters_4')
    op.drop_index('idx_clusters_5_centroid', table_name='clusters_5')
    op.drop_index('idx_clusters_6_centroid', table_name='clusters_6')
    op.drop_index('idx_clusters_7_centroid', table_name='clusters_7')
    op.drop_index('idx_clusters_8_centroid', table_name='clusters_8')
    op.drop_index('idx_clusters_9_centroid', table_name='clusters_9')
    op.drop_index('idx_event_locations_geo', table_name='event_locations')
    op.drop_index('idx_event_locations_version_geo', table_name='event_locations_version')
    op.add_column('rrules', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('rrules_event_id_fkey', 'rrules', type_='foreignkey')
    op.create_foreign_key(None, 'rrules', 'events', ['id'], ['id'])
    op.drop_column('rrules', 'event_id')
    op.add_column('rrules_version', sa.Column('id', sa.Integer(), autoincrement=False, nullable=False))
    op.drop_column('rrules_version', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rrules_version', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('rrules_version', 'id')
    op.add_column('rrules', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rrules', type_='foreignkey')
    op.create_foreign_key('rrules_event_id_fkey', 'rrules', 'events', ['event_id'], ['id'])
    op.drop_column('rrules', 'id')
    op.create_index('idx_event_locations_version_geo', 'event_locations_version', ['geo'], unique=False)
    op.create_index('idx_event_locations_geo', 'event_locations', ['geo'], unique=False)
    op.create_index('idx_clusters_9_centroid', 'clusters_9', ['centroid'], unique=False)
    op.create_index('idx_clusters_8_centroid', 'clusters_8', ['centroid'], unique=False)
    op.create_index('idx_clusters_7_centroid', 'clusters_7', ['centroid'], unique=False)
    op.create_index('idx_clusters_6_centroid', 'clusters_6', ['centroid'], unique=False)
    op.create_index('idx_clusters_5_centroid', 'clusters_5', ['centroid'], unique=False)
    op.create_index('idx_clusters_4_centroid', 'clusters_4', ['centroid'], unique=False)
    op.create_index('idx_clusters_3_centroid', 'clusters_3', ['centroid'], unique=False)
    op.create_index('idx_clusters_2_centroid', 'clusters_2', ['centroid'], unique=False)
    op.create_index('idx_clusters_16_centroid', 'clusters_16', ['centroid'], unique=False)
    op.create_index('idx_clusters_15_centroid', 'clusters_15', ['centroid'], unique=False)
    op.create_index('idx_clusters_14_centroid', 'clusters_14', ['centroid'], unique=False)
    op.create_index('idx_clusters_13_centroid', 'clusters_13', ['centroid'], unique=False)
    op.create_index('idx_clusters_12_centroid', 'clusters_12', ['centroid'], unique=False)
    op.create_index('idx_clusters_11_centroid', 'clusters_11', ['centroid'], unique=False)
    op.create_index('idx_clusters_10_centroid', 'clusters_10', ['centroid'], unique=False)
    # ### end Alembic commands ###
