"""empty message

Revision ID: 5cc1e3fd6c1a
Revises: a5c1be1e7891
Create Date: 2024-01-31 04:41:01.201162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc1e3fd6c1a'
down_revision = 'a5c1be1e7891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('youtube_url', sa.String(), nullable=True))
    op.add_column('events_version', sa.Column('youtube_url', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'youtube_url')
    op.drop_column('events', 'youtube_url')
    # ### end Alembic commands ###
