"""empty message

Revision ID: 6ee378b84f77
Revises: 66b35054f1b9
Create Date: 2021-12-11 19:37:46.148223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ee378b84f77'
down_revision = '66b35054f1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_edits', sa.Column('creator_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'suggested_edits', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suggested_edits', type_='foreignkey')
    op.drop_column('suggested_edits', 'creator_id')
    # ### end Alembic commands ###
