"""empty message

Revision ID: 72977f71675b
Revises: 466b435f3676
Create Date: 2023-10-02 07:35:47.956531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72977f71675b'
down_revision = '466b435f3676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('event_contribution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'event_contributions', ['event_contribution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'event_contribution_id')
    # ### end Alembic commands ###
