"""empty message

Revision ID: 7703499bf5ab
Revises: 0a68369a5897
Create Date: 2022-02-10 11:22:57.391856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7703499bf5ab'
down_revision = '0a68369a5897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('thumb_xxs_filename', sa.String(), nullable=True))
    op.add_column('media_items_version', sa.Column('thumb_xxs_filename', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items_version', 'thumb_xxs_filename')
    op.drop_column('media_items', 'thumb_xxs_filename')
    # ### end Alembic commands ###
