"""empty message

Revision ID: 7b6adc205de6
Revises: 27f2400c56cd
Create Date: 2021-12-14 18:09:45.907277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6adc205de6'
down_revision = '27f2400c56cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rrules', sa.Column('time', sa.String(), nullable=True))
    op.add_column('rrules_version', sa.Column('time', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rrules_version', 'time')
    op.drop_column('rrules', 'time')
    # ### end Alembic commands ###
