"""empty message

Revision ID: 8183b79f840a
Revises: 466b435f3676
Create Date: 2023-10-02 07:39:21.930212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8183b79f840a'
down_revision = '466b435f3676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('event_contribution_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'event_contributions', ['event_contribution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'event_contribution_id')
    # ### end Alembic commands ###
