"""empty message

Revision ID: 82c2ac06ce09
Revises: 3ddc424be5f3
Create Date: 2023-04-03 09:14:55.717055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82c2ac06ce09'
down_revision = '3ddc424be5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_urls_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('url', sa.String(), autoincrement=False, nullable=True),
    sa.Column('type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_artist_urls_version_end_transaction_id'), 'artist_urls_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_artist_urls_version_operation_type'), 'artist_urls_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_artist_urls_version_transaction_id'), 'artist_urls_version', ['transaction_id'], unique=False)
    op.create_table('user_event_date_going_table_version',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_date_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_user_event_date_going_table_version_end_transaction_id'), 'user_event_date_going_table_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_event_date_going_table_version_operation_type'), 'user_event_date_going_table_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_user_event_date_going_table_version_transaction_id'), 'user_event_date_going_table_version', ['transaction_id'], unique=False)
    op.create_table('user_event_date_interested_table_version',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_date_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_user_event_date_interested_table_version_end_transaction_id'), 'user_event_date_interested_table_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_event_date_interested_table_version_operation_type'), 'user_event_date_interested_table_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_user_event_date_interested_table_version_transaction_id'), 'user_event_date_interested_table_version', ['transaction_id'], unique=False)
    op.create_table('user_event_date_going_table',
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('event_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['event_dates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_event_date_interested_table',
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('event_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['event_dates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('email_actions', sa.Column('actioned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_actions', 'actioned')
    op.drop_table('user_event_date_interested_table')
    op.drop_table('user_event_date_going_table')
    op.drop_index(op.f('ix_user_event_date_interested_table_version_transaction_id'), table_name='user_event_date_interested_table_version')
    op.drop_index(op.f('ix_user_event_date_interested_table_version_operation_type'), table_name='user_event_date_interested_table_version')
    op.drop_index(op.f('ix_user_event_date_interested_table_version_end_transaction_id'), table_name='user_event_date_interested_table_version')
    op.drop_table('user_event_date_interested_table_version')
    op.drop_index(op.f('ix_user_event_date_going_table_version_transaction_id'), table_name='user_event_date_going_table_version')
    op.drop_index(op.f('ix_user_event_date_going_table_version_operation_type'), table_name='user_event_date_going_table_version')
    op.drop_index(op.f('ix_user_event_date_going_table_version_end_transaction_id'), table_name='user_event_date_going_table_version')
    op.drop_table('user_event_date_going_table_version')
    op.drop_index(op.f('ix_artist_urls_version_transaction_id'), table_name='artist_urls_version')
    op.drop_index(op.f('ix_artist_urls_version_operation_type'), table_name='artist_urls_version')
    op.drop_index(op.f('ix_artist_urls_version_end_transaction_id'), table_name='artist_urls_version')
    op.drop_table('artist_urls_version')
    # ### end Alembic commands ###
