"""empty message

Revision ID: 8d03dd3bf560
Revises: 00d3babaf02c
Create Date: 2021-09-03 11:23:04.168493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8d03dd3bf560"
down_revision = "00d3babaf02c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("message", sa.Text(), nullable=True))
    op.drop_constraint("reports_media_item_id_fkey", "reports", type_="foreignkey")
    op.drop_constraint(
        "reports_event_contribution_id_fkey", "reports", type_="foreignkey"
    )
    op.drop_column("reports", "description")
    op.drop_column("reports", "event_contribution_id")
    op.drop_column("reports", "media_item_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column(
            "media_item_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "reports",
        sa.Column(
            "event_contribution_id",
            postgresql.UUID(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "reports",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "reports_event_contribution_id_fkey",
        "reports",
        "event_contributions",
        ["event_contribution_id"],
        ["id"],
    )
    op.create_foreign_key(
        "reports_media_item_id_fkey",
        "reports",
        "media_items",
        ["media_item_id"],
        ["id"],
    )
    op.drop_column("reports", "message")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
