"""empty message

Revision ID: 8f57b9b69a09
Revises: 522ec5e30dd0
Create Date: 2024-11-03 20:59:53.430191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f57b9b69a09'
down_revision = '522ec5e30dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('description_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.add_column('artists', sa.Column('disambiguation_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.add_column('artists_version', sa.Column('description_translations', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('artists_version', sa.Column('disambiguation_translations', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tags', sa.Column('tag_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))

    # Migrate data to new translaction dicts
    connection = op.get_bind()
    

    # Artists
    results = connection.execute(sa.text("SELECT id, description, disambiguation FROM artists")).fetchall()
    
    for row in results:
        connection.execute(
            sa.text("UPDATE artists SET disambiguation_translations = :translations WHERE id = :id"),
            {"translations": {"en": row.disambiguation}, "id": row.id}
        )
        connection.execute(
            sa.text("UPDATE artists SET description_translations = :translations WHERE id = :id"),
            {"translations": {"en": row.description}, "id": row.id}
        )
    # tags
    results = connection.execute(sa.text("SELECT tag FROM tags")).fetchall()
    
    for row in results:
        connection.execute(
            sa.text("UPDATE tags SET tag_translations = :translations WHERE tag = :tag"),
            {"translations": {"en": row.tag}, "tag": row.tag}
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'tag_translations')
    op.drop_column('artists_version', 'disambiguation_translations')
    op.drop_column('artists_version', 'description_translations')
    op.drop_column('artists', 'disambiguation_translations')
    op.drop_column('artists', 'description_translations')
    # ### end Alembic commands ###
