"""empty message

Revision ID: 96dc1162c5e1
Revises: d233b54b7462
Create Date: 2021-12-20 12:05:33.591007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96dc1162c5e1'
down_revision = 'd233b54b7462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_page_views_table',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_page_views_table')
    # ### end Alembic commands ###
