"""empty message

Revision ID: 97dbf5be6c96
Revises: 1d2dad4acddc
Create Date: 2025-06-27 04:58:07.992651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dbf5be6c96'
down_revision = '1d2dad4acddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_reviews', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_reviews', 'event_reviews', ['parent_id'], ['id'])
    op.drop_column('event_reviews', 'rating')
    op.add_column('event_reviews_version', sa.Column('parent_id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('event_reviews_version', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_reviews_version', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('event_reviews_version', 'parent_id')
    op.add_column('event_reviews', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_reviews', type_='foreignkey')
    op.drop_column('event_reviews', 'parent_id')
    # ### end Alembic commands ###
