"""empty message

Revision ID: a4bb40da99b4
Revises: 616314189e7b
Create Date: 2021-12-06 13:19:28.274073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bb40da99b4'
down_revision = '616314189e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_edits', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.alter_column('suggested_edits', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'suggested_edits', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suggested_edits', type_='foreignkey')
    op.alter_column('suggested_edits', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('suggested_edits', 'artist_id')
    # ### end Alembic commands ###
