"""empty message

Revision ID: a5c1be1e7891
Revises: 8183b79f840a
Create Date: 2023-11-14 09:53:32.721499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5c1be1e7891'
down_revision = '8183b79f840a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('one_off_auth_token', postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'one_off_auth_token')
    # ### end Alembic commands ###
