"""empty message

Revision ID: a943734c3e35
Revises: 05ec1ee13039
Create Date: 2021-04-28 22:52:11.948894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a943734c3e35"
down_revision = "05ec1ee13039"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_clusters_10_centroid", table_name="clusters_10")
    op.drop_index("idx_clusters_11_centroid", table_name="clusters_11")
    op.drop_index("idx_clusters_12_centroid", table_name="clusters_12")
    op.drop_index("idx_clusters_13_centroid", table_name="clusters_13")
    op.drop_index("idx_clusters_14_centroid", table_name="clusters_14")
    op.drop_index("idx_clusters_15_centroid", table_name="clusters_15")
    op.drop_index("idx_clusters_16_centroid", table_name="clusters_16")
    op.drop_index("idx_clusters_2_centroid", table_name="clusters_2")
    op.drop_index("idx_clusters_3_centroid", table_name="clusters_3")
    op.drop_index("idx_clusters_4_centroid", table_name="clusters_4")
    op.drop_index("idx_clusters_5_centroid", table_name="clusters_5")
    op.drop_index("idx_clusters_6_centroid", table_name="clusters_6")
    op.drop_index("idx_clusters_7_centroid", table_name="clusters_7")
    op.drop_index("idx_clusters_8_centroid", table_name="clusters_8")
    op.drop_index("idx_clusters_9_centroid", table_name="clusters_9")
    op.add_column("event_dates", sa.Column("end", sa.DateTime(), nullable=True))
    op.add_column("event_dates", sa.Column("end_naive", sa.DateTime(), nullable=True))
    op.add_column("event_dates", sa.Column("start", sa.DateTime(), nullable=False))
    op.add_column(
        "event_dates", sa.Column("start_naive", sa.DateTime(), nullable=False)
    )
    op.drop_column("event_dates", "event_start")
    op.drop_column("event_dates", "event_end_naive")
    op.drop_column("event_dates", "event_start_naive")
    op.drop_column("event_dates", "event_end")
    op.add_column(
        "event_dates_version",
        sa.Column("end", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event_dates_version",
        sa.Column("end_naive", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event_dates_version",
        sa.Column("start", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event_dates_version",
        sa.Column("start_naive", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.drop_column("event_dates_version", "event_end_naive")
    op.drop_column("event_dates_version", "event_start_naive")
    op.drop_column("event_dates_version", "event_start")
    op.drop_column("event_dates_version", "event_end")
    op.add_column("event_locations", sa.Column("country", sa.String(), nullable=True))
    op.drop_index("idx_event_locations_geo", table_name="event_locations")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_event_locations_geo", "event_locations", ["geo"], unique=False)
    op.drop_column("event_locations", "country")
    op.add_column(
        "event_dates_version",
        sa.Column(
            "event_end", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "event_dates_version",
        sa.Column(
            "event_start", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "event_dates_version",
        sa.Column(
            "event_start_naive",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "event_dates_version",
        sa.Column(
            "event_end_naive",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("event_dates_version", "start_naive")
    op.drop_column("event_dates_version", "start")
    op.drop_column("event_dates_version", "end_naive")
    op.drop_column("event_dates_version", "end")
    op.add_column(
        "event_dates",
        sa.Column(
            "event_end", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "event_dates",
        sa.Column(
            "event_start_naive",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "event_dates",
        sa.Column(
            "event_end_naive",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "event_dates",
        sa.Column(
            "event_start", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("event_dates", "start_naive")
    op.drop_column("event_dates", "start")
    op.drop_column("event_dates", "end_naive")
    op.drop_column("event_dates", "end")
    op.create_index("idx_clusters_9_centroid", "clusters_9", ["centroid"], unique=False)
    op.create_index("idx_clusters_8_centroid", "clusters_8", ["centroid"], unique=False)
    op.create_index("idx_clusters_7_centroid", "clusters_7", ["centroid"], unique=False)
    op.create_index("idx_clusters_6_centroid", "clusters_6", ["centroid"], unique=False)
    op.create_index("idx_clusters_5_centroid", "clusters_5", ["centroid"], unique=False)
    op.create_index("idx_clusters_4_centroid", "clusters_4", ["centroid"], unique=False)
    op.create_index("idx_clusters_3_centroid", "clusters_3", ["centroid"], unique=False)
    op.create_index("idx_clusters_2_centroid", "clusters_2", ["centroid"], unique=False)
    op.create_index(
        "idx_clusters_16_centroid", "clusters_16", ["centroid"], unique=False
    )
    op.create_index(
        "idx_clusters_15_centroid", "clusters_15", ["centroid"], unique=False
    )
    op.create_index(
        "idx_clusters_14_centroid", "clusters_14", ["centroid"], unique=False
    )
    op.create_index(
        "idx_clusters_13_centroid", "clusters_13", ["centroid"], unique=False
    )
    op.create_index(
        "idx_clusters_12_centroid", "clusters_12", ["centroid"], unique=False
    )
    op.create_index(
        "idx_clusters_11_centroid", "clusters_11", ["centroid"], unique=False
    )
    op.create_index(
        "idx_clusters_10_centroid", "clusters_10", ["centroid"], unique=False
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
