"""empty message

Revision ID: b0da8c191b81
Revises: 2f7da62f5bc8
Create Date: 2023-06-15 07:49:44.310460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0da8c191b81'
down_revision = '2f7da62f5bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_dates', sa.Column('date_confirmed', sa.Boolean(), nullable=True))
    op.add_column('event_dates_version', sa.Column('date_confirmed', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('rrules', sa.Column('exact', sa.Boolean(), nullable=True))
    op.add_column('rrules_version', sa.Column('exact', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rrules_version', 'exact')
    op.drop_column('rrules', 'exact')
    op.drop_column('event_dates_version', 'date_confirmed')
    op.drop_column('event_dates', 'date_confirmed')
    # ### end Alembic commands ###
