"""empty message

Revision ID: c562f788e39a
Revises: c9f60f284c4a
Create Date: 2021-08-03 12:40:37.237804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c562f788e39a"
down_revision = "c9f60f284c4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("event_dates_creator_id_fkey", "event_dates", type_="foreignkey")
    op.drop_column("event_dates", "creator_id")
    op.drop_column("event_dates_version", "creator_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_dates_version",
        sa.Column("creator_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "event_dates",
        sa.Column("creator_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "event_dates_creator_id_fkey", "event_dates", "users", ["creator_id"], ["id"]
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
