"""empty message

Revision ID: c6a669b9024d
Revises: 5cc1e3fd6c1a
Create Date: 2024-02-23 05:57:20.672559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6a669b9024d'
down_revision = '5cc1e3fd6c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('media_items_version', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items_version', 'attributes')
    op.drop_column('media_items', 'attributes')
    # ### end Alembic commands ###
