"""empty message

Revision ID: ce4e74083eab
Revises: c6a669b9024d
Create Date: 2024-02-24 06:21:28.562963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4e74083eab'
down_revision = 'c6a669b9024d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('media_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'media_items', ['media_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'media_item_id')
    # ### end Alembic commands ###
