"""empty message

Revision ID: dc4a2252f424
Revises: 6ba3231bca57
Create Date: 2024-08-01 01:26:32.239899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc4a2252f424'
down_revision = '6ba3231bca57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_review_downvotes',
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('event_review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_review_id'], ['event_reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('event_review_upvotes',
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('event_review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_review_id'], ['event_reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column('event_reviews', 'status')
    op.drop_column('event_reviews', 'hotness')
    op.drop_column('event_reviews_version', 'status')
    op.drop_column('event_reviews_version', 'hotness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_reviews_version', sa.Column('hotness', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('event_reviews_version', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('event_reviews', sa.Column('hotness', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('event_reviews', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_table('event_review_upvotes')
    op.drop_table('event_review_downvotes')
    # ### end Alembic commands ###
