from pmapi.validate import allowed_file
import os
from flask import current_app, flash
from PIL import Image
import base64
from mimetypes import guess_extension
import uuid
import re
from flask_login import current_user
from .model import EventImage
from pmapi.extensions import db


def add_images_to_event(event, images, text=None, creator=current_user):
    event_images = []
    for i in images:
        file = i["base64Image"]
        filename, thumb_filename = save_event_image(file, event.id)
        event_image = EventImage(
            event_id=event.id,
            caption=i["caption"],
            filename=filename,
            thumb_filename=thumb_filename,
            creator=creator,
        )
        event_images.append(event_image)
        db.session.add(event_image)
    db.session.commit()
    return event_images


def save_event_image(file, eventId):

    mimetype = file[file.find("data:") + 5 : file.find(";base64,")]
    file_extension = guess_extension(mimetype)
    if file_extension == ".jpe":
        file_extension = ".jpg"
    unique_filename = str(uuid.uuid4())

    if file and allowed_file(file_extension):
        filename = unique_filename + file_extension
        thumb_filename = unique_filename + "_small" + file_extension
        print("extension:" + file_extension)
        print("filename: " + filename)
        print("thumb_filename:" + thumb_filename)
        path = os.path.join(
            current_app.config["IMAGE_UPLOAD_FOLDER"]
            + str("event/")
            + str(eventId)
            + str("/")
        )

        if not (os.path.exists(path)):
            # create the directory you want to save to
            os.makedirs(path)

        image_string = re.search(r"base64,(.*)", file).group(1)
        # the string generated by the client includes the mimetype
        # which ISNT in base64.
        # this gets the main base64 string
        with open(os.path.join(path, filename), "wb") as fh:
            fh.write(base64.b64decode(image_string))

        """
        resize to square
        thumb = ImageOps.fit(
            Image.open(
                os.path.join(path, filename)
                ),
            (512, 512),
            Image.ANTIALIAS)
        """
        img = Image.open(os.path.join(path, filename))
        img.thumbnail((250, 250), Image.ANTIALIAS)
        img.save(os.path.join(path, thumb_filename))

        return filename, thumb_filename

    else:
        flash("No selected file")
        return None, None
