"""empty message

Revision ID: 02d27a42d856
Revises: 000cd5209f06
Create Date: 2021-12-04 15:56:52.138706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d27a42d856'
down_revision = '000cd5209f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('area', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'area')
    # ### end Alembic commands ###
