"""empty message

Revision ID: 0a68369a5897
Revises: 5c868ae9fc4c
Create Date: 2021-12-30 18:25:18.202398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a68369a5897'
down_revision = '5c868ae9fc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rrules_event_id_fkey', 'rrules', type_='foreignkey')
    op.drop_column('rrules', 'event_id')
    op.drop_column('rrules_version', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rrules_version', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rrules', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('rrules_event_id_fkey', 'rrules', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
