"""empty message

Revision ID: 3abde8f1ffcb
Revises: 69f0f7f1a22b
Create Date: 2021-12-14 18:19:09.835920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abde8f1ffcb'
down_revision = '69f0f7f1a22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_default_location_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'default_url')
    op.drop_column('events', 'default_location_id')
    op.drop_column('events', 'default_ticket_url')
    op.drop_column('events_version', 'default_url')
    op.drop_column('events_version', 'default_location_id')
    op.drop_column('events_version', 'default_ticket_url')
    op.add_column('rrules', sa.Column('default_location_id', sa.Integer(), nullable=True))
    op.add_column('rrules', sa.Column('default_ticket_url', sa.String(), nullable=True))
    op.add_column('rrules', sa.Column('default_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'rrules', 'event_locations', ['default_location_id'], ['id'])
    op.add_column('rrules_version', sa.Column('default_location_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('rrules_version', sa.Column('default_ticket_url', sa.String(), autoincrement=False, nullable=True))
    op.add_column('rrules_version', sa.Column('default_url', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rrules_version', 'default_url')
    op.drop_column('rrules_version', 'default_ticket_url')
    op.drop_column('rrules_version', 'default_location_id')
    op.drop_constraint(None, 'rrules', type_='foreignkey')
    op.drop_column('rrules', 'default_url')
    op.drop_column('rrules', 'default_ticket_url')
    op.drop_column('rrules', 'default_location_id')
    op.add_column('events_version', sa.Column('default_ticket_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('default_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events_version', sa.Column('default_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('default_ticket_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('default_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('default_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_default_location_id_fkey', 'events', 'event_locations', ['default_location_id'], ['id'])
    # ### end Alembic commands ###
