"""empty message

Revision ID: 3ddc424be5f3
Revises: 7703499bf5ab
Create Date: 2022-02-15 12:29:21.325384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddc424be5f3'
down_revision = '7703499bf5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('popularity', sa.Integer(), nullable=True))
    op.add_column('artists_version', sa.Column('popularity', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists_version', 'popularity')
    op.drop_column('artists', 'popularity')
    # ### end Alembic commands ###
