"""empty message

Revision ID: 52c8e9c70f99
Revises: 3ddc424be5f3
Create Date: 2022-05-21 11:33:27.769332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c8e9c70f99'
down_revision = '3ddc424be5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_actions', sa.Column(
        'actioned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_actions', 'actioned')
    # ### end Alembic commands ###
