"""empty message

Revision ID: 55053bc1a28d
Revises: c8d56af8ca0e
Create Date: 2021-12-23 20:04:30.883558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55053bc1a28d'
down_revision = 'c8d56af8ca0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_date_artists', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('event_date_artists_version', sa.Column('stage', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_date_artists_version', 'stage')
    op.drop_column('event_date_artists', 'stage')
    # ### end Alembic commands ###
