"""empty message

Revision ID: 616314189e7b
Revises: 02d27a42d856
Create Date: 2021-12-06 13:12:46.930961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616314189e7b'
down_revision = '02d27a42d856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media_items', 'artists', ['artist_id'], ['id'])
    op.add_column('media_items_version', sa.Column('artist_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items_version', 'artist_id')
    op.drop_constraint(None, 'media_items', type_='foreignkey')
    op.drop_column('media_items', 'artist_id')
    # ### end Alembic commands ###
