"""empty message

Revision ID: 621c517dc54b
Revises: 2b2c563827ad
Create Date: 2021-12-26 18:34:34.780772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '621c517dc54b'
down_revision = '2b2c563827ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_tags_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('creator_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_artist_tags_version_end_transaction_id'), 'artist_tags_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_artist_tags_version_operation_type'), 'artist_tags_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_artist_tags_version_transaction_id'), 'artist_tags_version', ['transaction_id'], unique=False)
    op.create_table('artist_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=20), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_tags')
    op.drop_index(op.f('ix_artist_tags_version_transaction_id'), table_name='artist_tags_version')
    op.drop_index(op.f('ix_artist_tags_version_operation_type'), table_name='artist_tags_version')
    op.drop_index(op.f('ix_artist_tags_version_end_transaction_id'), table_name='artist_tags_version')
    op.drop_table('artist_tags_version')
    # ### end Alembic commands ###
