"""empty message

Revision ID: 66b35054f1b9
Revises: a4bb40da99b4
Create Date: 2021-12-10 14:30:22.796182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66b35054f1b9'
down_revision = 'a4bb40da99b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_following_table_version',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_user_event_following_table_version_end_transaction_id'), 'user_event_following_table_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_event_following_table_version_operation_type'), 'user_event_following_table_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_user_event_following_table_version_transaction_id'), 'user_event_following_table_version', ['transaction_id'], unique=False)
    op.create_table('user_event_following_table',
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('events', sa.Column('host_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['host_id'], ['id'])
    op.add_column('events_version', sa.Column('host_id', postgresql.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_version', 'host_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'host_id')
    op.drop_table('user_event_following_table')
    op.drop_index(op.f('ix_user_event_following_table_version_transaction_id'), table_name='user_event_following_table_version')
    op.drop_index(op.f('ix_user_event_following_table_version_operation_type'), table_name='user_event_following_table_version')
    op.drop_index(op.f('ix_user_event_following_table_version_end_transaction_id'), table_name='user_event_following_table_version')
    op.drop_table('user_event_following_table_version')
    # ### end Alembic commands ###
