"""empty message

Revision ID: 7242ba3a5ac5
Revises: 45465c516e6e
Create Date: 2021-12-01 16:05:30.344272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7242ba3a5ac5'
down_revision = '45465c516e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('disambiguation', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'disambiguation')
    # ### end Alembic commands ###
