"""empty message

Revision ID: 925bf6134a63
Revises: de521bd1d588
Create Date: 2021-12-15 10:02:14.855143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '925bf6134a63'
down_revision = 'de521bd1d588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('short_name')
    )
    op.create_table('regions',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.Column('country_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.short_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localities',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.Column('country_id', sa.String(), nullable=True),
    sa.Column('region_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.short_name'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event_locations', sa.Column('country_id', sa.String(), nullable=True))
    op.add_column('event_locations', sa.Column('locality_id', postgresql.UUID(), nullable=True))
    op.add_column('event_locations', sa.Column('region_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'event_locations', 'countries', ['country_id'], ['short_name'])
    op.create_foreign_key(None, 'event_locations', 'localities', ['locality_id'], ['id'])
    op.create_foreign_key(None, 'event_locations', 'regions', ['region_id'], ['id'])
    op.drop_column('event_locations', 'country_code')
    op.drop_column('event_locations', 'city')
    op.drop_column('event_locations', 'country')
    op.add_column('event_locations_version', sa.Column('country_id', sa.String(), autoincrement=False, nullable=True))
    op.add_column('event_locations_version', sa.Column('locality_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('event_locations_version', sa.Column('region_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('event_locations_version', 'country_code')
    op.drop_column('event_locations_version', 'city')
    op.drop_column('event_locations_version', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_locations_version', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_locations_version', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_locations_version', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event_locations_version', 'region_id')
    op.drop_column('event_locations_version', 'locality_id')
    op.drop_column('event_locations_version', 'country_id')
    op.add_column('event_locations', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_locations', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event_locations', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_locations', type_='foreignkey')
    op.drop_constraint(None, 'event_locations', type_='foreignkey')
    op.drop_constraint(None, 'event_locations', type_='foreignkey')
    op.drop_column('event_locations', 'region_id')
    op.drop_column('event_locations', 'locality_id')
    op.drop_column('event_locations', 'country_id')
    op.drop_table('localities')
    op.drop_table('regions')
    op.drop_table('countries')
    # ### end Alembic commands ###
