"""empty message

Revision ID: 95bfec51215e
Revises: 621c517dc54b
Create Date: 2021-12-26 20:07:25.600929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bfec51215e'
down_revision = '621c517dc54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('thumb_xs_filename', sa.String(), nullable=True))
    op.add_column('media_items_version', sa.Column('thumb_xs_filename', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items_version', 'thumb_xs_filename')
    op.drop_column('media_items', 'thumb_xs_filename')
    # ### end Alembic commands ###
