"""empty message

Revision ID: a3d9ebe1eb4c
Revises: 8f00db9070d1
Create Date: 2021-11-26 16:28:39.124072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3d9ebe1eb4c'
down_revision = '8f00db9070d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mbid', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('soundcloud_url', sa.String(length=200), nullable=True),
    sa.Column('spotify_url', sa.String(length=200), nullable=True),
    sa.Column('bandcamp_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_date_artists_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('event_date_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('creator_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_event_date_artists_version_end_transaction_id'), 'event_date_artists_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_event_date_artists_version_operation_type'), 'event_date_artists_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_event_date_artists_version_transaction_id'), 'event_date_artists_version', ['transaction_id'], unique=False)
    op.create_table('event_date_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('event_date_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_date_id'], ['event_dates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_date_artists')
    op.drop_index(op.f('ix_event_date_artists_version_transaction_id'), table_name='event_date_artists_version')
    op.drop_index(op.f('ix_event_date_artists_version_operation_type'), table_name='event_date_artists_version')
    op.drop_index(op.f('ix_event_date_artists_version_end_transaction_id'), table_name='event_date_artists_version')
    op.drop_table('event_date_artists_version')
    op.drop_table('artists')
    # ### end Alembic commands ###
