"""empty message

Revision ID: c685c063644d
Revises: 2d09fb096713
Create Date: 2021-11-22 23:10:13.102240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID


# revision identifiers, used by Alembic.
revision = "c685c063644d"
down_revision = "2d09fb096713"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("suggested_edits", sa.Column("approved_by_id", UUID, nullable=True))
    op.create_foreign_key(None, "suggested_edits", "users", ["approved_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "suggested_edits", type_="foreignkey")
    op.drop_column("suggested_edits", "approved_by_id")
    # ### end Alembic commands ###
