"""empty message

Revision ID: d233b54b7462
Revises: 925bf6134a63
Create Date: 2021-12-17 16:47:52.932469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd233b54b7462'
down_revision = '925bf6134a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_favorites_table_version',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_user_event_favorites_table_version_end_transaction_id'), 'user_event_favorites_table_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_event_favorites_table_version_operation_type'), 'user_event_favorites_table_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_user_event_favorites_table_version_transaction_id'), 'user_event_favorites_table_version', ['transaction_id'], unique=False)
    op.create_table('user_event_favorites_table',
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_event_favorites_table')
    op.drop_index(op.f('ix_user_event_favorites_table_version_transaction_id'), table_name='user_event_favorites_table_version')
    op.drop_index(op.f('ix_user_event_favorites_table_version_operation_type'), table_name='user_event_favorites_table_version')
    op.drop_index(op.f('ix_user_event_favorites_table_version_end_transaction_id'), table_name='user_event_favorites_table_version')
    op.drop_table('user_event_favorites_table_version')
    # ### end Alembic commands ###
