"""empty message

Revision ID: de521bd1d588
Revises: 14e83424094d
Create Date: 2021-12-15 00:45:40.662813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de521bd1d588"
down_revision = "14e83424094d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    suggestion_status = postgresql.ENUM(
        "approved", "hidden", "pending", name="suggestion_status"
    )
    suggestion_status.create(op.get_bind())
    op.add_column(
        "suggested_edits",
        sa.Column(
            "status",
            sa.Enum("approved", "hidden", "pending", name="suggestion_status"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suggested_edits", "status")
    suggestion_status = postgresql.ENUM(
        "approved", "hidden", "pending", name="suggestion_status"
    )
    suggestion_status.drop(op.get_bind())
    # ### end Alembic commands ###
