"""empty message

Revision ID: 4f0077e3335b
Revises: e8043d2a4cc2
Create Date: 2021-10-21 11:51:18.396807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0077e3335b'
down_revision = 'e8043d2a4cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rrules_version',
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('recurring_type', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('separation_count', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('week_of_month', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('day_of_month', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('month_of_year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'transaction_id')
    )
    op.create_index(op.f('ix_rrules_version_end_transaction_id'), 'rrules_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_rrules_version_operation_type'), 'rrules_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_rrules_version_transaction_id'), 'rrules_version', ['transaction_id'], unique=False)
    op.drop_index('idx_clusters_10_centroid', table_name='clusters_10')
    op.drop_index('idx_clusters_11_centroid', table_name='clusters_11')
    op.drop_index('idx_clusters_12_centroid', table_name='clusters_12')
    op.drop_index('idx_clusters_13_centroid', table_name='clusters_13')
    op.drop_index('idx_clusters_14_centroid', table_name='clusters_14')
    op.drop_index('idx_clusters_15_centroid', table_name='clusters_15')
    op.drop_index('idx_clusters_16_centroid', table_name='clusters_16')
    op.drop_index('idx_clusters_2_centroid', table_name='clusters_2')
    op.drop_index('idx_clusters_3_centroid', table_name='clusters_3')
    op.drop_index('idx_clusters_4_centroid', table_name='clusters_4')
    op.drop_index('idx_clusters_5_centroid', table_name='clusters_5')
    op.drop_index('idx_clusters_6_centroid', table_name='clusters_6')
    op.drop_index('idx_clusters_7_centroid', table_name='clusters_7')
    op.drop_index('idx_clusters_8_centroid', table_name='clusters_8')
    op.drop_index('idx_clusters_9_centroid', table_name='clusters_9')
    op.drop_index('idx_event_locations_geo', table_name='event_locations')
    op.drop_index('idx_event_locations_version_geo', table_name='event_locations_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_event_locations_version_geo', 'event_locations_version', ['geo'], unique=False)
    op.create_index('idx_event_locations_geo', 'event_locations', ['geo'], unique=False)
    op.create_index('idx_clusters_9_centroid', 'clusters_9', ['centroid'], unique=False)
    op.create_index('idx_clusters_8_centroid', 'clusters_8', ['centroid'], unique=False)
    op.create_index('idx_clusters_7_centroid', 'clusters_7', ['centroid'], unique=False)
    op.create_index('idx_clusters_6_centroid', 'clusters_6', ['centroid'], unique=False)
    op.create_index('idx_clusters_5_centroid', 'clusters_5', ['centroid'], unique=False)
    op.create_index('idx_clusters_4_centroid', 'clusters_4', ['centroid'], unique=False)
    op.create_index('idx_clusters_3_centroid', 'clusters_3', ['centroid'], unique=False)
    op.create_index('idx_clusters_2_centroid', 'clusters_2', ['centroid'], unique=False)
    op.create_index('idx_clusters_16_centroid', 'clusters_16', ['centroid'], unique=False)
    op.create_index('idx_clusters_15_centroid', 'clusters_15', ['centroid'], unique=False)
    op.create_index('idx_clusters_14_centroid', 'clusters_14', ['centroid'], unique=False)
    op.create_index('idx_clusters_13_centroid', 'clusters_13', ['centroid'], unique=False)
    op.create_index('idx_clusters_12_centroid', 'clusters_12', ['centroid'], unique=False)
    op.create_index('idx_clusters_11_centroid', 'clusters_11', ['centroid'], unique=False)
    op.create_index('idx_clusters_10_centroid', 'clusters_10', ['centroid'], unique=False)
    op.drop_index(op.f('ix_rrules_version_transaction_id'), table_name='rrules_version')
    op.drop_index(op.f('ix_rrules_version_operation_type'), table_name='rrules_version')
    op.drop_index(op.f('ix_rrules_version_end_transaction_id'), table_name='rrules_version')
    op.drop_table('rrules_version')
    # ### end Alembic commands ###
