"""empty message

Revision ID: 59c429d588aa
Revises: 4f0077e3335b
Create Date: 2021-11-08 21:38:07.714264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "59c429d588aa"
down_revision = "4f0077e3335b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_items_version",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("creator_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("caption", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("position", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("thumb_filename", sa.String(), autoincrement=False, nullable=True),
        sa.Column("image_filename", sa.String(), autoincrement=False, nullable=True),
        sa.Column(
            "video_low_filename", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "video_med_filename", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "video_high_filename", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "video_poster_filename", sa.String(), autoincrement=False, nullable=True
        ),
        sa.Column("duration", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "contribution_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column("event_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("event_date_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_media_items_version_end_transaction_id"),
        "media_items_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_items_version_operation_type"),
        "media_items_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_items_version_transaction_id"),
        "media_items_version",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_media_items_version_transaction_id"), table_name="media_items_version"
    )
    op.drop_index(
        op.f("ix_media_items_version_operation_type"), table_name="media_items_version"
    )
    op.drop_index(
        op.f("ix_media_items_version_end_transaction_id"),
        table_name="media_items_version",
    )
    op.drop_table("media_items_version")
    # ### end Alembic commands ###
