"""empty message

Revision ID: ab81bd10877c
Revises: 59c429d588aa
Create Date: 2021-11-08 21:42:16.698600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab81bd10877c'
down_revision = '59c429d588aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items_version', sa.Column('type', sa.Enum('image', 'video', name='media_type'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items_version', 'type')
    # ### end Alembic commands ###
